[0m08:44:17.716979 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x103622b10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105d4d940>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105d4d670>]}


============================== 08:44:17.719686 | 1028df1d-c162-4489-a9fe-e4c7abb8c20c ==============================
[0m08:44:17.719686 [info ] [MainThread]: Running with dbt=1.8.6
[0m08:44:17.720007 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/Users/brossierlucas/.dbt', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt run', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m08:44:17.720300 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/brossierlucas/programmation/moovai_pipeline_test/src/01_ingestion/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m08:44:17.721535 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.03913, "process_user_time": 0.575159, "process_kernel_time": 0.091642, "process_mem_max_rss": "91750400", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m08:44:17.721817 [debug] [MainThread]: Command `dbt run` failed at 08:44:17.721765 after 0.04 seconds
[0m08:44:17.721988 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104750a70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105d4d700>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105d4d9d0>]}
[0m08:44:17.722141 [debug] [MainThread]: Flushing usage events
[0m11:33:19.813514 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x102909970>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1046645f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104a75cd0>]}


============================== 11:33:19.816413 | 38795472-3a73-4eb7-872f-c92442bca164 ==============================
[0m11:33:19.816413 [info ] [MainThread]: Running with dbt=1.8.6
[0m11:33:19.816764 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/brossierlucas/.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt run --select src_listen.sql', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m11:33:19.817063 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/brossierlucas/programmation/moovai_pipeline_test/src/01_ingestion/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:33:19.818404 [debug] [MainThread]: Resource report: {"command_name": "run", "command_wall_clock_time": 0.036787584, "process_user_time": 0.576175, "process_kernel_time": 0.089311, "process_mem_max_rss": "93274112", "command_success": false, "process_in_blocks": "0", "process_out_blocks": "0"}
[0m11:33:19.818722 [debug] [MainThread]: Command `dbt run` failed at 11:33:19.818666 after 0.04 seconds
[0m11:33:19.818920 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104704d70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1040105c0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104a77cb0>]}
[0m11:33:19.819097 [debug] [MainThread]: Flushing usage events
